/**
 * Marriage system for the Palusteria simulation.
 *
 * Handles:
 *   - Cultural marriage rules (Sauromatian polygyny vs. Imanian monogamy)
 *   - Eligibility checks (age, sex, blood relation, spouse limits)
 *   - Performing a marriage and generating opinion ripple effects
 *   - Querying a person's current marriageability
 *
 * All functions here are pure — they receive state values and return result
 * objects without mutating anything. The Zustand store applies all changes.
 *
 * Source: PALUSTERIA_GAME_DESIGN.md §4.1, PALUSTERIA_ARCHITECTURE.md §4.1.
 * No React / DOM / store imports — pure simulation logic.
 */

import type { Person } from './person';
import type { GameState, EventRecord, Household, HouseholdRole, HouseholdTradition } from '../turn/game-state';
import type { CultureId } from '../turn/game-state';
import type { TraitId } from '../personality/traits';
import { CONVERSATIONAL_THRESHOLD } from '../culture/language-acquisition';
import { SAUROMATIAN_CULTURE_IDS } from './culture';
import { getSauromatianFraction, getImanianFraction } from '../genetics/gender-ratio';
import { createHousehold, addToHousehold, countWives, mergeHouseholds, deriveHouseholdName } from './household';
import { getEffectiveOpinion, MARRIAGE_REFUSAL_THRESHOLD } from './opinions';

// ─── Marriage Types ───────────────────────────────────────────────────────────

/**
 * Cultural marriage rules for a given tradition.
 *
 * Sauromatian: polygynous — one man may take up to 6 wives; concubines are not
 *   a recognised Sauromatian institution.
 * Imanian: nominally monogamous — 1 wife; Ansberite colonial practice quietly
 *   permits up to 2 concubines (additional spouseIds beyond the first).
 */
export interface MarriageRules {
  /** The cultural tradition these rules derive from. */
  tradition: 'sauromatian' | 'imanian' | 'ansberite';
  /** Maximum number of wives a man may take under this tradition. */
  maxWives: number;
  /** Maximum concubines permitted beyond wives (Imanian only). */
  maxConcubines: number;
  /** Whether hearth-companions (Ansberite blended tradition) are permitted. */
  allowsHearthCompanion: boolean;
}

/**
 * Summary of a person's current marriage eligibility.
 * Returned by `getMarriageability()` for UI display and AI queries.
 */
export interface MarriageInfo {
  /** Whether this person can currently enter a new marriage. */
  isEligible: boolean;
  /** How many spouseIds the person currently has. */
  currentSpouseCount: number;
  /** The maximum number of spouses permitted under their cultural rules. */
  maxSpouses: number;
  /** The cultural identity used to determine marriage rules. */
  culturalContext: CultureId;
  /** Human-readable reason if not eligible. Undefined when eligible. */
  blockedReason?: string;
}

/**
 * The outcome of a successfully performed marriage.
 *
 * The caller (game store) should:
 *   1. Replace personA and personB in `GameState.people` with their updated versions.
 *   2. Apply each opinionChange by updating `people.get(observerId).relationships`.
 *   3. Append `eventRecord` to `GameState.eventHistory`.
 *   4. Set `state.households.set(household.id, household)` to persist the household.
 */
export interface MarriageResult {
  /** Updated copy of personA with the new spouse added to spouseIds. */
  updatedPersonA: Person;
  /** Updated copy of personB with the new spouse added to spouseIds. */
  updatedPersonB: Person;
  /**
   * Opinion changes generated by this marriage for bystanders.
   * Only populated for cross-cultural marriages.
   */
  opinionChanges: Array<{ observerId: string; targetId: string; delta: number }>;
  /** Event record logging this marriage for history and event-chain queries. */
  eventRecord: EventRecord;
  /** The resulting household (created or updated). Caller must persist to state.households. */
  household: Household;
  /** True if this marriage created a brand-new household; false if an existing one was updated. */
  householdCreated: boolean;
  /**
   * ID of the household that was dissolved during the marriage merge.
   * null when there was no household to dissolve (e.g. both parties had none).
   */
  dissolvedHouseholdId: string | null;
}

// ─── Language Compatibility ──────────────────────────────────────────────────

/**
 * The degree to which two prospective spouses share a common language.
 *
 * - 'shared'  — both have fluency ≥ CONVERSATIONAL_THRESHOLD in the same language
 * - 'partial' — one person can converse in a language the other understands only
 *               a little (0 < fluency < threshold); communication is effortful
 * - 'none'    — no linguistic overlap whatsoever
 */
export type LanguageCompatibility = 'shared' | 'partial' | 'none';

/**
 * Evaluates the language compatibility between two prospective spouses.
 *
 * @param a - One of the two people.
 * @param b - The other person.
 * @returns The degree of shared linguistic understanding.
 */
export function getLanguageCompatibility(a: Person, b: Person): LanguageCompatibility {
  const aFluency = new Map(a.languages.map(l => [l.language, l.fluency]));
  const bFluency = new Map(b.languages.map(l => [l.language, l.fluency]));

  // Check for a truly shared language (both conversational)
  for (const [lang, fluency] of aFluency) {
    if (fluency >= CONVERSATIONAL_THRESHOLD && (bFluency.get(lang) ?? 0) >= CONVERSATIONAL_THRESHOLD) {
      return 'shared';
    }
  }

  // Check for partial understanding (one conversational, other has any knowledge)
  for (const [lang, fluency] of aFluency) {
    if (fluency >= CONVERSATIONAL_THRESHOLD && (bFluency.get(lang) ?? 0) > 0) {
      return 'partial';
    }
  }
  for (const [lang, fluency] of bFluency) {
    if (fluency >= CONVERSATIONAL_THRESHOLD && (aFluency.get(lang) ?? 0) > 0) {
      return 'partial';
    }
  }

  return 'none';
}

// ─── Cultural Rules ───────────────────────────────────────────────────────────

/**
 * Returns the marriage rules appropriate for the given person, taking into
 * account both their primary culture and their bloodline heritage.
 *
 * Three tiers:
 *
 * **Sauromatian** — primary culture is Sauromatian/settlement_native AND
 *   Imanian bloodline fraction < 30%. The full wife-council model: up to 6
 *   wives. Concubines are not a Sauromatian institution.
 *
 * **Ansberite** — the colonial hybrid tier, reached in two ways:
 *   (a) Primary culture is Sauromatian but Imanian bloodline ≥ 30% — the man
 *       is culturally Sauromatian but his blood still carries Imanian norms;
 *   (b) Primary culture is Imanian but Sauromatian bloodline ≥ 30% — the man
 *       hasn't culturally shifted yet, but his mixed heritage pulls him toward
 *       multi-wife practice before the full cultural transition happens.
 *   → Up to 2 wives, 2 concubines, hearth-companions permitted.
 *
 * **Imanian** — primary culture is Imanian AND Sauromatian bloodline < 30%.
 *   One wife; up to 2 concubines; hearth-companions not recognised.
 *
 * Women's spouse count is always capped at 1 regardless of which rules apply —
 * this asymmetry is enforced in `canMarry()`, not here.
 *
 * @param man - The person whose rules are being evaluated.
 * @returns The applicable MarriageRules.
 */
export function getMarriageRules(man: Person): MarriageRules {
  const sauroFrac = getSauromatianFraction(man.heritage.bloodline);
  const imanFrac  = getImanianFraction(man.heritage.bloodline);
  const isSauroCulture =
    SAUROMATIAN_CULTURE_IDS.has(man.heritage.primaryCulture) ||
    man.heritage.primaryCulture === 'settlement_native';

  // Full Sauromatian: culturally Sauromatian with predominantly Sauromatian blood
  if (isSauroCulture && imanFrac < 0.3) {
    return { tradition: 'sauromatian', maxWives: 6, maxConcubines: 0, allowsHearthCompanion: false };
  }

  // Ansberite hybrid: either culture has shifted but blood is still mixed,
  // or blood is mixed enough to adopt multi-wife norms before full cultural shift
  if (isSauroCulture || sauroFrac >= 0.3) {
    return { tradition: 'ansberite', maxWives: 2, maxConcubines: 2, allowsHearthCompanion: true };
  }

  // Imanian default: culturally Imanian with low Sauromatian bloodline
  return { tradition: 'imanian', maxWives: 1, maxConcubines: 2, allowsHearthCompanion: false };
}

// ─── Eligibility ──────────────────────────────────────────────────────────────

/**
 * Checks whether two people may marry each other under the current game rules.
 *
 * Checks performed (in order):
 *   1. Must be opposite sex.
 *   2. Both must be at least 16 years old.
 *   3. Must not share a parent (sibling / half-sibling check on parentIds).
 *   4. Spouse-slot check based on the man's cultural rules and the woman's
 *      current marital status.
 *
 * @param personA - One of the two prospective spouses.
 * @param personB - The other prospective spouse.
 * @param state - Current game state (used to look up people for relation checks).
 * @returns An object indicating whether the marriage is permitted, and if not, why.
 */
export function canMarry(
  personA: Person,
  personB: Person,
  state: GameState,
): { allowed: boolean; reason?: string } {
  // 1. Must be opposite sex
  if (personA.sex === personB.sex) {
    return { allowed: false, reason: 'same_sex' };
  }

  // 2. Both must be of marriageable age
  if (personA.age < 16 || personB.age < 16) {
    return { allowed: false, reason: 'underage' };
  }

  // 3. No shared parents — prevent incest (parent, sibling, half-sibling)
  // Direct parent-child check
  const aParents = personA.parentIds.filter((id): id is string => id !== null);
  const bParents = personB.parentIds.filter((id): id is string => id !== null);

  if (aParents.includes(personB.id) || bParents.includes(personA.id)) {
    return { allowed: false, reason: 'too_closely_related' };
  }

  // Sibling / half-sibling: any non-null parentId in common
  for (const aParentId of aParents) {
    if (bParents.includes(aParentId)) {
      return { allowed: false, reason: 'too_closely_related' };
    }
  }

  // 3.5 Opinion gate — either party refuses if they hold a strongly negative
  // opinion of the other (below the MARRIAGE_REFUSAL_THRESHOLD).
  const man = personA.sex === 'male' ? personA : personB;
  const woman = personA.sex === 'female' ? personA : personB;

  if (getEffectiveOpinion(man, woman.id) < MARRIAGE_REFUSAL_THRESHOLD) {
    return { allowed: false, reason: 'unwilling_party' };
  }
  if (getEffectiveOpinion(woman, man.id) < MARRIAGE_REFUSAL_THRESHOLD) {
    return { allowed: false, reason: 'unwilling_party' };
  }

  // 4. Apply spouse-slot limits using the already-identified man and woman

  // Women may only have one spouse under any cultural tradition
  if (woman.spouseIds.length >= 1) {
    return { allowed: false, reason: 'woman_already_married' };
  }

  // Man's limit is determined by his cultural rules
  const rules = getMarriageRules(man);
  const manMaxSpouses = rules.maxWives + rules.maxConcubines;
  if (man.spouseIds.length >= manMaxSpouses) {
    return { allowed: false, reason: 'man_at_spouse_limit' };
  }

  // Household wife-capacity check (if a household already exists)
  if (man.householdId) {
    const household = state.households.get(man.householdId);
    if (household && countWives(household, state) >= rules.maxWives) {
      return { allowed: false, reason: 'household_at_wife_capacity' };
    }
  }

  return { allowed: true };
}

// ─── Marriage Execution ───────────────────────────────────────────────────────

/**
 * Performs a marriage between two people and returns the resulting state changes.
 *
 * Precondition: `canMarry(personA, personB, state).allowed === true`.
 * This function does not re-validate — the caller must check first.
 *
 * Cross-cultural opinion effects (when man's and woman's culturalIdentity differ):
 *   - Bystanders with the 'traditional' trait who share the groom's culture:
 *     opinion toward the groom −10 (disapproval of marrying outside the culture)
 *   - Bystanders with the 'cosmopolitan' trait who share the groom's culture:
 *     opinion toward the groom +5 (approval of cultural openness)
 *
 * @param personA - One of the two people to marry.
 * @param personB - The other person to marry.
 * @param state - Current game state (read-only — for bystander iteration).
 * @returns A MarriageResult describing all state changes to apply.
 */
export function performMarriage(
  personA: Person,
  personB: Person,
  state: GameState,
): MarriageResult {
  const man = personA.sex === 'male' ? personA : personB;
  const woman = personA.sex === 'female' ? personA : personB;

  // Determine which tradition governs household direction
  const womanIsSauromatian =
    SAUROMATIAN_CULTURE_IDS.has(woman.heritage.primaryCulture) ||
    woman.heritage.primaryCulture === 'settlement_native';
  const tradition: HouseholdTradition = womanIsSauromatian ? 'sauromatian' : 'imanian';

  // ── Merge households ────────────────────────────────────────────────────────
  // Under the new lifecycle system BOTH parties already have a household.
  // Sauromatian: man joins woman's household.  Imanian/Ansberite: woman joins man's.
  let household: Household;
  let householdCreated = false;
  let dissolvedHouseholdId: string | null = null;

  const manHousehold   = man.householdId   ? state.households.get(man.householdId)   : null;
  const womanHousehold = woman.householdId ? state.households.get(woman.householdId) : null;

  if (tradition === 'sauromatian') {
    // Woman's household receives; man's dissolves (or is created if missing)
    if (womanHousehold && manHousehold && womanHousehold.id !== manHousehold.id) {
      const merge = mergeHouseholds(
        womanHousehold.id, manHousehold.id,
        state.households, state.people,
      );
      household = merge.updatedHouseholds.get(womanHousehold.id) ?? womanHousehold;
      dissolvedHouseholdId = merge.dissolvedHouseholdId;
    } else if (womanHousehold) {
      household = addToHousehold(womanHousehold, man.id);
    } else {
      const created = createHousehold({
        name: '',
        tradition,
        headId: man.id,
        seniorWifeId: woman.id,
        foundedTurn: state.turnNumber,
        isAutoNamed: true,
      });
      household = addToHousehold(addToHousehold(created, man.id), woman.id);
      householdCreated = true;
    }
    // Ensure head & seniorWife are set
    if (!household.headId) household = { ...household, headId: man.id };
    if (!household.seniorWifeId) household = { ...household, seniorWifeId: woman.id };
  } else {
    // Imanian / Ansberite: man's household receives; woman's dissolves
    if (manHousehold && womanHousehold && manHousehold.id !== womanHousehold.id) {
      const merge = mergeHouseholds(
        manHousehold.id, womanHousehold.id,
        state.households, state.people,
      );
      household = merge.updatedHouseholds.get(manHousehold.id) ?? manHousehold;
      dissolvedHouseholdId = merge.dissolvedHouseholdId;
    } else if (manHousehold) {
      household = addToHousehold(manHousehold, woman.id);
    } else {
      const created = createHousehold({
        name: '',
        tradition,
        headId: man.id,
        seniorWifeId: woman.id,
        foundedTurn: state.turnNumber,
        isAutoNamed: true,
      });
      household = addToHousehold(addToHousehold(created, man.id), woman.id);
      householdCreated = true;
    }
    // Ensure head & seniorWife are set
    if (!household.headId) household = { ...household, headId: man.id };
    if (!household.seniorWifeId) household = { ...household, seniorWifeId: woman.id };
  }

  // Designate first wife if none yet
  if (!household.seniorWifeId) {
    household = { ...household, seniorWifeId: woman.id };
  }

  // Refresh auto-name
  const nameMap = new Map(state.people);
  nameMap.set(man.id, man);
  nameMap.set(woman.id, woman);
  if (household.isAutoNamed) {
    household = { ...household, name: deriveHouseholdName(household, nameMap) };
  }

  // Determine each person's household role
  const womanRole: HouseholdRole =
    household.seniorWifeId === woman.id ? 'senior_wife' : 'wife';

  // Apply spouse links and household membership to both persons
  const updatedPersonA: Person = {
    ...personA,
    spouseIds: [...personA.spouseIds, personB.id],
    householdId: household.id,
    householdRole: personA.sex === 'male' ? 'head' : womanRole,
  };
  const updatedPersonB: Person = {
    ...personB,
    spouseIds: [...personB.spouseIds, personA.id],
    householdId: household.id,
    householdRole: personB.sex === 'male' ? 'head' : womanRole,
  };

  const isCrossCultural = personA.heritage.primaryCulture !== personB.heritage.primaryCulture;

  const opinionChanges: MarriageResult['opinionChanges'] = [];

  if (isCrossCultural) {
    for (const observer of state.people.values()) {
      // Skip the couple themselves
      if (observer.id === personA.id || observer.id === personB.id) continue;
      // Only people who share the groom's culture are affected
      if (observer.heritage.primaryCulture !== man.heritage.primaryCulture) continue;

      if (observer.traits.includes('traditional' as TraitId)) {
        opinionChanges.push({ observerId: observer.id, targetId: man.id, delta: -10 });
      }
      if (observer.traits.includes('cosmopolitan' as TraitId)) {
        opinionChanges.push({ observerId: observer.id, targetId: man.id, delta: +5 });
      }
    }
  }

  const eventRecord: EventRecord = {
    eventId: 'marriage',
    turnNumber: state.turnNumber,
    choiceId: 'performed',
    involvedPersonIds: [personA.id, personB.id],
  };

  return { updatedPersonA, updatedPersonB, opinionChanges, eventRecord, household, householdCreated, dissolvedHouseholdId };
}

// ─── Marriageability Query ────────────────────────────────────────────────────

/**
 * Returns a summary of whether a person is currently eligible to marry and why.
 *
 * Useful for UI filtering (greying out ineligible pairings) and AI queries.
 * Does not check the *other* party — use `canMarry()` for pair-specific checks.
 *
 * @param person - The person to evaluate.
 * @param _state - Current game state (reserved for future relation-graph queries).
 * @returns A MarriageInfo summary.
 */
// ─── Informal Unions ─────────────────────────────────────────────────────────

/**
 * The relationship style for a woman entering a household as an informal partner.
 *
 * concubine        — Sauromatian or Imanian tradition; recognised but below wife rank.
 * hearth_companion — Ansberite blended tradition; a woman with her own economic standing.
 */
export type InformalUnionStyle = 'concubine' | 'hearth_companion';

/** The outcome of forming a concubine / hearth-companion relationship. */
export interface InformalUnionResult {
  updatedMan: Person;
  updatedWoman: Person;
  household: Household;
  householdCreated: boolean;
}

/**
 * Checks whether a man and woman may form an informal union.
 * Applies the same opinion gate as formal marriage: either party may refuse
 * if their opinion of the other is below MARRIAGE_REFUSAL_THRESHOLD.
 */
export function canFormInformalUnion(
  man: Person,
  woman: Person,
): { allowed: boolean; reason?: string } {
  if (man.age < 16 || woman.age < 16) {
    return { allowed: false, reason: 'underage' };
  }
  if (getEffectiveOpinion(man, woman.id) < MARRIAGE_REFUSAL_THRESHOLD) {
    return { allowed: false, reason: 'unwilling_party' };
  }
  if (getEffectiveOpinion(woman, man.id) < MARRIAGE_REFUSAL_THRESHOLD) {
    return { allowed: false, reason: 'unwilling_party' };
  }
  return { allowed: true };
}

/**
 * Forms a concubine or hearth-companion relationship between a man and a woman.
 *
 * Unlike formal marriage this does NOT add spouseIds.
 * If the man has no household one is created with him as head.
 *
 * @param man   - The household head (must be male).
 * @param woman - The woman entering the household.
 * @param style - Union style ('concubine' or 'hearth_companion').
 * @param state - Current game state (for household lookup).
 * @returns An InformalUnionResult; caller must persist household and updated persons.
 */
export function formConcubineRelationship(
  man: Person,
  woman: Person,
  style: InformalUnionStyle,
  state: GameState,
): InformalUnionResult {
  let household: Household;
  let householdCreated: boolean;
  const existingHousehold = man.householdId
    ? (state.households.get(man.householdId) ?? null)
    : null;

  if (existingHousehold) {
    household = addToHousehold(existingHousehold, woman.id);
    householdCreated = false;
  } else {
    const womanIsSauromatian =
      SAUROMATIAN_CULTURE_IDS.has(woman.heritage.primaryCulture) ||
      woman.heritage.primaryCulture === 'settlement_native';
    const tradition: HouseholdTradition = womanIsSauromatian ? 'sauromatian' : 'imanian';
    const householdName =
      tradition === 'sauromatian'
        ? `${woman.familyName ?? woman.givenName} Ashkaran`
        : `House of ${man.familyName ?? man.givenName}`;
    const created = createHousehold({
      name: householdName,
      tradition,
      headId: man.id,
      seniorWifeId: null,
      foundedTurn: state.turnNumber,
    });
    household = addToHousehold(addToHousehold(created, man.id), woman.id);
    householdCreated = true;
  }

  const updatedMan: Person = {
    ...man,
    householdId: household.id,
    householdRole: man.householdRole ?? 'head',
  };
  const updatedWoman: Person = {
    ...woman,
    householdId: household.id,
    householdRole: style,
  };

  return { updatedMan, updatedWoman, household, householdCreated };
}

// ─── Marriageability Query ────────────────────────────────────────────────────

export function getMarriageability(person: Person, _state: GameState): MarriageInfo {
  const currentSpouseCount = person.spouseIds.length;
  const culturalContext = person.heritage.primaryCulture;

  // Women's cap is always 1 regardless of culture
  if (person.sex === 'female') {
    const maxSpouses = 1;
    const isEligible = person.age >= 16 && currentSpouseCount < maxSpouses;
    return {
      isEligible,
      currentSpouseCount,
      maxSpouses,
      culturalContext,
      blockedReason: !isEligible
        ? currentSpouseCount >= maxSpouses ? 'woman_already_married' : 'underage'
        : undefined,
    };
  }

  // Men: apply cultural rules
  const rules = getMarriageRules(person);
  const maxSpouses = rules.maxWives + rules.maxConcubines;
  const isEligible = person.age >= 16 && currentSpouseCount < maxSpouses;

  return {
    isEligible,
    currentSpouseCount,
    maxSpouses,
    culturalContext,
    blockedReason: !isEligible
      ? currentSpouseCount >= maxSpouses ? 'man_at_spouse_limit' : 'underage'
      : undefined,
  };
}
