/**
 * Marriage system for the Palusteria simulation.
 *
 * Handles:
 *   - Cultural marriage rules (Sauromatian polygyny vs. Imanian monogamy)
 *   - Eligibility checks (age, sex, blood relation, spouse limits)
 *   - Performing a marriage and generating opinion ripple effects
 *   - Querying a person's current marriageability
 *
 * All functions here are pure — they receive state values and return result
 * objects without mutating anything. The Zustand store applies all changes.
 *
 * Source: PALUSTERIA_GAME_DESIGN.md §4.1, PALUSTERIA_ARCHITECTURE.md §4.1.
 * No React / DOM / store imports — pure simulation logic.
 */

import type { Person } from './person';
import type { GameState, EventRecord } from '../turn/game-state';
import type { CultureId } from '../turn/game-state';
import type { TraitId } from '../personality/traits';
import { CONVERSATIONAL_THRESHOLD } from '../culture/language-acquisition';

// ─── Marriage Types ───────────────────────────────────────────────────────────

/**
 * Cultural marriage rules for a given tradition.
 *
 * Sauromatian: polygynous — one man may take up to 6 wives; concubines are not
 *   a recognised Sauromatian institution.
 * Imanian: nominally monogamous — 1 wife; Ansberite colonial practice quietly
 *   permits up to 2 concubines (additional spouseIds beyond the first).
 */
export interface MarriageRules {
  /** The cultural tradition these rules derive from. */
  tradition: 'sauromatian' | 'imanian';
  /** Maximum number of wives a man may take under this tradition. */
  maxWives: number;
  /** Maximum concubines permitted beyond wives (Imanian only). */
  maxConcubines: number;
}

/**
 * Summary of a person's current marriage eligibility.
 * Returned by `getMarriageability()` for UI display and AI queries.
 */
export interface MarriageInfo {
  /** Whether this person can currently enter a new marriage. */
  isEligible: boolean;
  /** How many spouseIds the person currently has. */
  currentSpouseCount: number;
  /** The maximum number of spouses permitted under their cultural rules. */
  maxSpouses: number;
  /** The cultural identity used to determine marriage rules. */
  culturalContext: CultureId;
  /** Human-readable reason if not eligible. Undefined when eligible. */
  blockedReason?: string;
}

/**
 * The outcome of a successfully performed marriage.
 *
 * The caller (game store) should:
 *   1. Replace personA and personB in `GameState.people` with their updated versions.
 *   2. Apply each opinionChange by updating `people.get(observerId).relationships`.
 *   3. Append `eventRecord` to `GameState.eventHistory`.
 */
export interface MarriageResult {
  /** Updated copy of personA with the new spouse added to spouseIds. */
  updatedPersonA: Person;
  /** Updated copy of personB with the new spouse added to spouseIds. */
  updatedPersonB: Person;
  /**
   * Opinion changes generated by this marriage for bystanders.
   * Only populated for cross-cultural marriages.
   */
  opinionChanges: Array<{ observerId: string; targetId: string; delta: number }>;
  /** Event record logging this marriage for history and event-chain queries. */
  eventRecord: EventRecord;
}

// ─── Language Compatibility ──────────────────────────────────────────────────

/**
 * The degree to which two prospective spouses share a common language.
 *
 * - 'shared'  — both have fluency ≥ CONVERSATIONAL_THRESHOLD in the same language
 * - 'partial' — one person can converse in a language the other understands only
 *               a little (0 < fluency < threshold); communication is effortful
 * - 'none'    — no linguistic overlap whatsoever
 */
export type LanguageCompatibility = 'shared' | 'partial' | 'none';

/**
 * Evaluates the language compatibility between two prospective spouses.
 *
 * @param a - One of the two people.
 * @param b - The other person.
 * @returns The degree of shared linguistic understanding.
 */
export function getLanguageCompatibility(a: Person, b: Person): LanguageCompatibility {
  const aFluency = new Map(a.languages.map(l => [l.language, l.fluency]));
  const bFluency = new Map(b.languages.map(l => [l.language, l.fluency]));

  // Check for a truly shared language (both conversational)
  for (const [lang, fluency] of aFluency) {
    if (fluency >= CONVERSATIONAL_THRESHOLD && (bFluency.get(lang) ?? 0) >= CONVERSATIONAL_THRESHOLD) {
      return 'shared';
    }
  }

  // Check for partial understanding (one conversational, other has any knowledge)
  for (const [lang, fluency] of aFluency) {
    if (fluency >= CONVERSATIONAL_THRESHOLD && (bFluency.get(lang) ?? 0) > 0) {
      return 'partial';
    }
  }
  for (const [lang, fluency] of bFluency) {
    if (fluency >= CONVERSATIONAL_THRESHOLD && (aFluency.get(lang) ?? 0) > 0) {
      return 'partial';
    }
  }

  return 'none';
}

// ─── Cultural Rules ───────────────────────────────────────────────────────────

/** CultureIds that follow Sauromatian polygynous marriage tradition. */
const SAUROMATIAN_CULTURES: ReadonlySet<CultureId> = new Set([
  'kiswani_traditional',
  'hanjoda_traditional',
  'kiswani_riverfolk',
  'kiswani_bayuk',
  'kiswani_haisla',
  'hanjoda_stormcaller',
  'hanjoda_bloodmoon',
  'hanjoda_talon',
  'hanjoda_emrasi',
  'sauro_borderfolk',
  'sauro_wildborn',
  'settlement_native',
]);

/**
 * Returns the marriage rules appropriate for the given cultural identity.
 *
 * Women's spouse count is always capped at 1 regardless of which rules apply —
 * this asymmetry is enforced in `canMarry()`, not here.
 *
 * @param primaryCulture - The CultureId of the person (typically the man).
 * @returns The applicable MarriageRules.
 */
export function getMarriageRules(primaryCulture: CultureId): MarriageRules {
  if (SAUROMATIAN_CULTURES.has(primaryCulture)) {
    return { tradition: 'sauromatian', maxWives: 6, maxConcubines: 0 };
  }
  // Imanian (imanian_homeland, ansberite) and townborn default
  return { tradition: 'imanian', maxWives: 1, maxConcubines: 2 };
}

// ─── Eligibility ──────────────────────────────────────────────────────────────

/**
 * Checks whether two people may marry each other under the current game rules.
 *
 * Checks performed (in order):
 *   1. Must be opposite sex.
 *   2. Both must be at least 16 years old.
 *   3. Must not share a parent (sibling / half-sibling check on parentIds).
 *   4. Spouse-slot check based on the man's cultural rules and the woman's
 *      current marital status.
 *
 * @param personA - One of the two prospective spouses.
 * @param personB - The other prospective spouse.
 * @param state - Current game state (used to look up people for relation checks).
 * @returns An object indicating whether the marriage is permitted, and if not, why.
 */
export function canMarry(
  personA: Person,
  personB: Person,
  state: GameState,
): { allowed: boolean; reason?: string } {
  // 1. Must be opposite sex
  if (personA.sex === personB.sex) {
    return { allowed: false, reason: 'same_sex' };
  }

  // 2. Both must be of marriageable age
  if (personA.age < 16 || personB.age < 16) {
    return { allowed: false, reason: 'underage' };
  }

  // 3. No shared parents — prevent incest (parent, sibling, half-sibling)
  // Direct parent-child check
  const aParents = personA.parentIds.filter((id): id is string => id !== null);
  const bParents = personB.parentIds.filter((id): id is string => id !== null);

  if (aParents.includes(personB.id) || bParents.includes(personA.id)) {
    return { allowed: false, reason: 'too_closely_related' };
  }

  // Sibling / half-sibling: any non-null parentId in common
  for (const aParentId of aParents) {
    if (bParents.includes(aParentId)) {
      return { allowed: false, reason: 'too_closely_related' };
    }
  }

  // Suppress unused-variable warning for state — future checks will use it
  // (e.g., checking for extended-family relations or culture-dependent bans).
  void state;

  // 4. Identify the man and woman, then apply spouse-slot limits
  const man = personA.sex === 'male' ? personA : personB;
  const woman = personA.sex === 'female' ? personA : personB;

  // Women may only have one spouse under any cultural tradition
  if (woman.spouseIds.length >= 1) {
    return { allowed: false, reason: 'woman_already_married' };
  }

  // Man's limit is determined by his cultural rules
  const rules = getMarriageRules(man.heritage.primaryCulture);
  const manMaxSpouses = rules.maxWives + rules.maxConcubines;
  if (man.spouseIds.length >= manMaxSpouses) {
    return { allowed: false, reason: 'man_at_spouse_limit' };
  }

  return { allowed: true };
}

// ─── Marriage Execution ───────────────────────────────────────────────────────

/**
 * Performs a marriage between two people and returns the resulting state changes.
 *
 * Precondition: `canMarry(personA, personB, state).allowed === true`.
 * This function does not re-validate — the caller must check first.
 *
 * Cross-cultural opinion effects (when man's and woman's culturalIdentity differ):
 *   - Bystanders with the 'traditional' trait who share the groom's culture:
 *     opinion toward the groom −10 (disapproval of marrying outside the culture)
 *   - Bystanders with the 'cosmopolitan' trait who share the groom's culture:
 *     opinion toward the groom +5 (approval of cultural openness)
 *
 * @param personA - One of the two people to marry.
 * @param personB - The other person to marry.
 * @param state - Current game state (read-only — for bystander iteration).
 * @returns A MarriageResult describing all state changes to apply.
 */
export function performMarriage(
  personA: Person,
  personB: Person,
  state: GameState,
): MarriageResult {
  const updatedPersonA: Person = {
    ...personA,
    spouseIds: [...personA.spouseIds, personB.id],
  };
  const updatedPersonB: Person = {
    ...personB,
    spouseIds: [...personB.spouseIds, personA.id],
  };

  const isCrossCultural = personA.heritage.primaryCulture !== personB.heritage.primaryCulture;
  const man = personA.sex === 'male' ? personA : personB;

  const opinionChanges: MarriageResult['opinionChanges'] = [];

  if (isCrossCultural) {
    for (const observer of state.people.values()) {
      // Skip the couple themselves
      if (observer.id === personA.id || observer.id === personB.id) continue;
      // Only people who share the groom's culture are affected
      if (observer.heritage.primaryCulture !== man.heritage.primaryCulture) continue;

      if (observer.traits.includes('traditional' as TraitId)) {
        opinionChanges.push({ observerId: observer.id, targetId: man.id, delta: -10 });
      }
      if (observer.traits.includes('cosmopolitan' as TraitId)) {
        opinionChanges.push({ observerId: observer.id, targetId: man.id, delta: +5 });
      }
    }
  }

  const eventRecord: EventRecord = {
    eventId: 'marriage',
    turnNumber: state.turnNumber,
    choiceId: 'performed',
    involvedPersonIds: [personA.id, personB.id],
  };

  return { updatedPersonA, updatedPersonB, opinionChanges, eventRecord };
}

// ─── Marriageability Query ────────────────────────────────────────────────────

/**
 * Returns a summary of whether a person is currently eligible to marry and why.
 *
 * Useful for UI filtering (greying out ineligible pairings) and AI queries.
 * Does not check the *other* party — use `canMarry()` for pair-specific checks.
 *
 * @param person - The person to evaluate.
 * @param _state - Current game state (reserved for future relation-graph queries).
 * @returns A MarriageInfo summary.
 */
export function getMarriageability(person: Person, _state: GameState): MarriageInfo {
  const currentSpouseCount = person.spouseIds.length;
  const culturalContext = person.heritage.primaryCulture;

  // Women's cap is always 1 regardless of culture
  if (person.sex === 'female') {
    const maxSpouses = 1;
    const isEligible = person.age >= 16 && currentSpouseCount < maxSpouses;
    return {
      isEligible,
      currentSpouseCount,
      maxSpouses,
      culturalContext,
      blockedReason: !isEligible
        ? currentSpouseCount >= maxSpouses ? 'woman_already_married' : 'underage'
        : undefined,
    };
  }

  // Men: apply cultural rules
  const rules = getMarriageRules(culturalContext);
  const maxSpouses = rules.maxWives + rules.maxConcubines;
  const isEligible = person.age >= 16 && currentSpouseCount < maxSpouses;

  return {
    isEligible,
    currentSpouseCount,
    maxSpouses,
    culturalContext,
    blockedReason: !isEligible
      ? currentSpouseCount >= maxSpouses ? 'man_at_spouse_limit' : 'underage'
      : undefined,
  };
}
